apiVersion: v2
name: observability
description: Kinetix Observability Stack
version: 0.1.0
appVersion: "1.0.0"
type: application

dependencies:
  - name: kube-prometheus-stack
    version: "~67.0"
    repository: "https://prometheus-community.github.io/helm-charts"
    condition: kube-prometheus-stack.enabled
  - name: loki
    version: "~6.0"
    repository: "https://grafana.github.io/helm-charts"
    condition: loki.enabled
  - name: tempo
    version: "~1.0"
    repository: "https://grafana.github.io/helm-charts"
    condition: tempo.enabled
  - name: opentelemetry-collector
    version: "~0.100"
    repository: "https://open-telemetry.github.io/opentelemetry-helm-charts"
    condition: opentelemetry-collector.enabled
