apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "kinetix.fullname" . }}-keycloak-realm
  labels:
    {{- include "kinetix.labels" . | nindent 4 }}
data:
  realm-export.json: |-
    {{- .Files.Get "files/realm-export.json" | nindent 4 }}
