apiVersion: v1
kind: Secret
metadata:
  name: kinetix-db-credentials
  labels:
    {{- include "kinetix.labels" . | nindent 4 }}
type: Opaque
stringData:
  username: {{ .Values.secrets.dbUsername | default "kinetix" }}
  password: {{ .Values.secrets.dbPassword | default "kinetix" }}
---
apiVersion: v1
kind: Secret
metadata:
  name: kinetix-keycloak-credentials
  labels:
    {{- include "kinetix.labels" . | nindent 4 }}
type: Opaque
stringData:
  admin-password: {{ .Values.secrets.keycloakAdminPassword | default "admin" }}
