replicaCount: 1

image:
  repository: kinetix/regulatory-service
  pullPolicy: IfNotPresent

service:
  type: ClusterIP
  port: 8085

env:
  PORT: "8085"
  OTEL_JAVA_GLOBAL_AUTOCONFIGURE_ENABLED: "true"
  OTEL_EXPORTER_OTLP_ENDPOINT: "http://kinetix-opentelemetry-collector:4317"
  OTEL_SERVICE_NAME: "regulatory-service"
  OTEL_LOGS_EXPORTER: "otlp"
  OTEL_METRICS_EXPORTER: "none"
  OTEL_TRACES_EXPORTER: "otlp"

resources:
  requests:
    cpu: 250m
    memory: 512Mi
  limits:
    cpu: "1"
    memory: 1Gi

autoscaling:
  enabled: false
  minReplicas: 1
  maxReplicas: 5
  targetCPUUtilizationPercentage: 70

probes:
  path: /health
